[tools]
node = "22"

[tasks.publish]
description = "build the publish"
run = [
  "yarn build:firefox",
  "yarn build:chrome",
  "python scripts/publish.py",
  "python scripts/distribute_firefox_src.py",
]
